### PR TITLE
Fix datetime fmt

### PR DESCRIPTION
**Pull request by pzabolotniy**
Here is fix for yaml-formatted config

### CODE REVIEW

**Comment by hhkbp2** [comment]
@pzabolotniy Could you update to the latest master code, and make a clean commit on latest code for this fix?

**Comment by pzabolotniy** [comment]
do you suggest me to update from your master branch?

**Comment by hhkbp2** [comment]
@pzabolotniy I would like you to make a clean PR with changes to the latest master code, so that it is more easy to review or merge the PR.

**Comment by pzabolotniy** [comment]
Made something, now PR contents only one file diff, but still has several commits.
is it ok?

**Comment by hhkbp2** [comment]
@pzabolotniy Merged. Cheers!

**Pull request merged**
