### PR TITLE
Add format support for goroutine id

### PR DESCRIPTION
**Pull request by vmarkovtsev**

### CODE REVIEW

**Comment by hhkbp2** [comment]
Hi @vmarkovtsev ,

I'm not sure whether you have read these discussions:

https://groups.google.com/forum/#!topic/golang-nuts/lGtALXDJQIE
https://groups.google.com/forum/#!topic/golang-nuts/Nt0hVV_nqHE

It seems that go-routine id is forbidden in golang. And there is no reliable/consistent method to get go-routine id at the latest versions of golang. So, I'm going to follow the golang principle on this and reject your PR.

Sometimes I hear from people who are using `go-logging` that they would like to have some thing like unique id to identify each goroutine. I would suggest a workaround to implement globally unique ids for goroutines in application level, instead of hacking the goroutine id in golang runtime. In this case, there wouldn't be any predefined format flag in `go-logging` for this id.

**Comment by vmarkovtsev** [comment]
Yes, sure I read these. Indeed, there is no pretty way to get goid. Indeed, Pike says I don't need it, etc.

But the problem is, principles are principles, but production is production. My service needs goid-s to diagnose hangs and deadlocks, estimate parallelism level at each moment of time and track the execution history. The reasons are basically the same as with threadid in C++. Python's coroutines like those in asyncio, Tornado, etc. are artificial and there is no such thing as ID even theoretically, and we previously suffered from inability to track the execution and "visualize" races.

This is not the first time someone god-like tells "how to do it right" - it's OK for him to have a strong opinion. Guido says in turn that "practicality beats purity". After all, programming is not something you try to copy as much as you can from others who claim what is right. When I used to be a middle developer some years ago, I actually followed best practices as much as I could, now I have my own vision of this (I don't mean I threw best practices away - they are still mostly useful).

I don't object to rejecting this PR. go-logging is BSD licensed, so no problem having my own fork. Thank you very much for your port, it saved me a ton of time!

P.S.
https://github.com/hhkbp2/go-logging/blob/master/LICENSE#L14 - {organization} template was not substituted

**Comment by hhkbp2** [comment]
Yeah, It's frustrating when the golang designers insist some principles that they feel right about, however these principles deviate our actual requirements when programming. I agree with you that design principles and the practicality should be adjusted to be compatible if they seems to be conflicting. I think the golang design team should be open to listen to different opinions, though they are famously stubborn.

Since there is no library API in golang to provide these guarantees:

1. each go-routine has a glabol unique id (so the user don't have to consider the possibility of the value of this id would not rewind during on run of the program if it overflows)
2. stable API to read go-routine id when golang self evolves to new versions
3. if the go-routine id increases monotonically during one run of the whole program, or even serval runs at different time, would be helpful to identify the sequencing of these go-routine in one same log file

it's somewhat tricky to hack the golang runtime to read the go-routine id. I don't think it's a good idea to add a dependency of some unspecified hehaviour of golang runtime to `go-logging`. For example, your PR works if and only if the stack format remains the same in the future golang versions. However this stack format is not specified or guaranteed to be consistent on next version of golang. 

If there is no perfect way to read go-routime id from the runtime, personly I would like to be practical and to implement it on application level, so that both the `go-logging` code and my app code using `go-logging` would stay solid even in the future.

So this PR is rejected due to the reason *"there is no good way to read go-routine id from runtime"*, rather than *"just blindly follow these principles which golang designer tell us"*. If you sometime find some good way to read go-routine id, please let me know and I'm happy to add a new format flag for it in `go-logging`.

Anyway, you are welcome to have your own fork if you still feel the need of this PR. BSD license is choosed specifically for your free usage of these code.

**Comment by hhkbp2** [comment]
Gonna close it. Leave a comment or reopen it if there is any further issue.

**Pull request closed without merging**
